### ISSUE TITLE
Move huggingface cache away from `/homes`

### ISSUE THREAD

**Issue by jantrienes** [IKIM-Essen/EMCP-config#143]
Huggingface keeps a cache of modes and datasets downloaded from the hub in `/homes/$USER/.cache/huggingface/`. 

This has two issues:
1. These artifacts are typically quite large. Because we do not cache the home directories, read/write of these files puts unnecessary pressure on NFS.
2. Users might pile up a lot of unused artifacts, which clutter up our disk space.

@enasca and I discussed a bit, and we came to the conclusion that we could move the cache to a location on `/local`. This has the downside that jobs may have to re-download models if it's the first time this job is run on a node. But either way, currently they have to be downloaded from NFS or from hub.

To avoid that local disk space clutters up, we can clean the cache for files not used in the past `N` days (e.g., every 21 days). Here is a sketch on how to do this using an official HF API:

```py
from datetime import datetime
from huggingface_hub import scan_cache_dir

expiry = 21  # in days
now = datetime.now()
cache_info = scan_cache_dir()

to_clean = []
for repo in cache_info.repos:
    delta = now - datetime.fromtimestamp(repo.last_accessed)
    if delta.days >= expiry:
        print(f"{repo.size_on_disk_str:>8}", f"{delta.days:>4} days", repo.repo_id)
        to_clean += [revision.commit_hash for revision in repo.revisions]

delete_strategy = cache_info.delete_revisions(*to_clean)
print(f"Will free {delete_strategy.expected_freed_size_str}.")
# delete_strategy.execute() <--- run this to execute transaction
```

<details>
<summary>Debug output on my user</summary>

```
   14.2G   65 days bigscience/bloomz-7b1
    4.9G   65 days bigscience/mt0-large
  440.7M  121 days bert-base-uncased
  440.7M  106 days microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext
  213.8K  137 days dmis-lab/biobert-base-cased-v1.1
   14.2G   65 days bigscience/bloomz-7b1-mt
  673.1M  121 days bert-base-multilingual-uncased
Will free 34.8G.
```

</details>

I also considered a simple bash script to identify old files, but I think it is safer to use the huggingface cache management API (i.e., less risk to leave the cache in a corrupted state).

---

To implement
1. Set a user-wide environment variable (e.g., `HF_CACHE=/local/hf-cache/$USER/`)
2. Create a daily cron job for above python script (should run in a conda? environment with `pip install huggingface_hub`)
3. Remove the now obsolete user cache in `/homes/$USER/.cache/huggingface/`

**Comment by jantrienes** [comment]
Cross ref to huggingface repo, asking for a cli option: https://github.com/huggingface/huggingface_hub/issues/1065

**Comment by osmalpkoras** [comment]
I'm in favor of doing this. This might become a pattern, so how about using `HF_CACHE=/local/cache/hugginface/$USER/` as the environment variabe?

Also, we might want to set one of the following environment variables instead:

- [`HF_HOME`](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/environment_variables#hfhome)
- [`XDG_CACHE_HOME`](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/environment_variables#xdgcachehome)
